[build]
  publish = "."
  command = "chmod +x install_flutter.sh && ./install_flutter.sh"

[[redirects]]
  from = "/app"
  to = "/app/index.html"
  status = 200

[[redirects]]
  from = "/app/*"
  to = "/app/index.html"
  status = 200
