[build]
  command = "bash ./install_flutter.sh && /opt/buildhome/flutter/bin/flutter build web --release"
  publish = "build/web"
  base = "."

[build.environment]
  # ✅ Stop Netlify from trying to install anything (Node, Yarn, Ruby, etc.)
  NETLIFY_SKIP_INSTALL = "true"
  NPM_FLAGS = "--version"
  NODE_VERSION = "18"
  NETLIFY_USE_YARN = "false"
  BUNDLE_BIN = "false"
  GEM_HOME = "/dev/null"
  BUNDLER_VERSION = "0"
  FLUTTER_HOME = "/opt/buildhome/flutter"
  PATH = "/opt/buildhome/flutter/bin:/opt/buildhome/flutter/bin/cache/dart-sdk/bin:/usr/local/bin:/usr/bin:/bin"
