[build]
  publish = "."
  command = "chmod +x install_flutter.sh && ./install_flutter.sh"

[build.environment]
  NETLIFY_SKIP_INSTALL = "true"

# ✅ Redirect rules for Flutter app under /app/
[[redirects]]
  from = "/app"
  to = "/app/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/app/"
  to = "/app/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/app/*"
  to = "/app/index.html"
  status = 200
  force = true
