[build]
  publish = "build/web"
  command = "bash install_flutter.sh"

[build.environment]
  # Disable all automatic dependency installation
  NETLIFY_USE_YARN = "false"
  NETLIFY_USE_NPM = "false" 
  NETLIFY_USE_BUNDLER = "false"
  NPM_FLAGS = "--version"  # Fake command to skip npm install
  YARN_FLAGS = "--version" # Fake command to skip yarn install
  
  # Flutter configuration
  FLUTTER_HOME = "/opt/buildhome/flutter"
  PATH = "/opt/buildhome/flutter/bin:/opt/buildhome/flutter/bin/cache/dart-sdk/bin:/usr/local/bin:/usr/bin:/bin"

[[plugins]]
  package = "@netlify/plugin-sitemap"