[build]
  command = "bash install_flutter.sh"
  publish = "build/web"
  ignore = "exit 0" # ensures deploy always runs

[build.environment]
  # 🚫 Disable automatic dependency install
  NETLIFY_USE_YARN = "false"
  NETLIFY_USE_NPM = "false"
  NETLIFY_USE_BUNDLER = "false"
  NETLIFY_SKIP_INSTALL = "true"
  NETLIFY_DISABLE_GEM_BUNDLER = "true"
  
  # 🚀 Flutter config
  FLUTTER_HOME = "/opt/buildhome/flutter"
  PATH = "/opt/buildhome/flutter/bin:/opt/buildhome/flutter/bin/cache/dart-sdk/bin:/usr/local/bin:/usr/bin:/bin"
