[build]
  publish = "build/web"
  command = "chmod +x install_flutter.sh && ./install_flutter.sh"

[build.environment]
  # Completely skip Netlify's dependency installation
  NETLIFY_SKIP_INSTALL = "true"
  
  # Flutter configuration
  FLUTTER_HOME = "/opt/buildhome/flutter"
  PATH = "/opt/buildhome/flutter/bin:/opt/buildhome/flutter/bin/cache/dart-sdk/bin:$PATH"