[build]
  command = "bash ./install_flutter.sh && flutter build web --release"
  publish = "build/web"

[build.environment]
  FLUTTER_VERSION = "3.24.3"


[build.lifecycle]
  onBuild = "bash ./install_flutter.sh"
