name: subtrack
description: A simple and elegant subscription tracker for web and iOS.

publish_to: "none" # prevents accidental publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.0
  flutter_riverpod: ^2.5.1
  intl: ^0.19.0
  fl_chart: ^0.66.2
  uuid: ^4.4.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
